[Interface]
PrivateKey = CLIENT_PRIVATE_KEY
Address = 10.6.0.2/24
DNS = 9.9.9.9, 149.112.112.112 # DNS might change depending on the provider (e.g. Cloudflare, Quad9).

[Peer]
PublicKey = SERVER_PUBLIC_KEY
Endpoint = yourdomain.duckdns.org:51820
AllowedIPs = 0.0.0.0/0
